### ISSUE TITLE
Adding a unique slug in Post entity

### ISSUE THREAD

**Issue by charlesen** [un-sam-sauvage/P6_snowtricks#8]
On aimerait pouvoir accéder à une figure en l'affichant à l'aide de son slug : 
- www.monsite.fr/posts/ma-jolie-figure (où `ma-jolie-figure` est le `slug` de la figure)

au lieu  de : 
- www.monsite.fr/posts/2 (où `2` est l'`id`de la figure)

Pour cela, suivons les étapes suivantes : 
- Création de la propriété `slug` dans l'entité Posts : `make entity` + migration dans la BDD
- On rend cette propriété unique (Voir l'exemple sur [la propriété username](https://github.com/un-sam-sauvage/P6_snowtricks/blob/main/src/Entity/User.php#L14))
- Dans le `PostsController`,  mettre en place la création du slug (methode `new`) ou sa mise à jour (methode `edit`) à l'aide du [SluggerInterface](https://symfony.com/doc/current/components/string.html#slugger)

```php
// ...
use Symfony\Component\String\Slugger\SluggerInterface;
// ...
        #[Route('/new', name: 'app_posts_new', methods: ['GET', 'POST'])]
	public function new(Request $request, PostsRepository $postsRepository, FileUploader $fileUploader, MediaRepository $mediaRepository, SluggerInterface $slugger): Response
	{
           // ...
           if ($form->isSubmitted() && $form->isValid()) {
                       $postName = $post->getName();
                       $slug = $slugger->slug($postName)->lower();
                       $post->setSlug($slug);
		       $postsRepository->save($post, true);
                  // ...
           }
           // ...
        }
```

**Comment by charlesen** [comment]
Dans l'entité Posts, on peut aussi rajouter la contrainte d'unicité pour qu'elle s'applique en BDD : 

```php
// src/Entity/Posts.php
#[ORM\Column(length: 255, unique: true)]
		private ?string $name = null;
```

**Comment by un-sam-sauvage** [comment]
Added
